apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pod-cleanup-monit
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/charlieshreck/monit_homelab.git
    targetRevision: main
    path: kubernetes/platform/pod-cleanup

  destination:
    server: https://10.10.0.30:6443
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
